version: '3'

services:
  prod:
    image: jesse-website
    container_name: jesse-website-prod
    env_file:
      - .env
    ports:
      - 3000:3000
  dev:
    image: jesse-website
    container_name: jesse-website-dev
    volumes:
      - ./app:/app # Mount a volume in the dev mode so we don't have to keep rebuilding the image
    env_file:
      - .env
    ports:
      - 3000:3000