name: DeployToHeroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.0 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jesse-website" #Must be unique in Heroku
          heroku_email: "jrbartola@gmail.com"
          branch: "master" #OPTIONAL and DEFAULT - 'HEAD' (a.k.a your current branch)
          usedocker: true #OPTIONAL and DEFAULT - false
